#!/bin/sh

case "$1" in
start)
    /usr/sbin/gen_fw_env.sh start
    ;;
stop)
    /usr/sbin/gen_fw_env.sh stop
    ;;
restart)
    "$0" stop
    "$0" start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
