require summitsom-mfg.conf

DISTRO = "summitsom-mfg-initramfs"
DISTRO_NAME = "Summit SOM Manufacturing Initramfs"

INITRAMFS_IMAGE = "image-summitsom-mfg-initramfs"

DISTROOVERRIDES .= ":summitsom-initramfs:summitsom-usb-boot:summitsom-mfg"
