PREFERRED_PROVIDER_u-boot-tools = "u-boot-summit-tools"
PREFERRED_PROVIDER_u-boot-tools-native = "u-boot-summit-tools-native"
PREFERRED_PROVIDER_nativesdk-u-boot-tools = "nativesdk-u-boot-summit-tools"

PREFERRED_PROVIDER_u-boot-mkimage = "u-boot-summit-tools"
PREFERRED_PROVIDER_u-boot-mkimage-native = "u-boot-summit-tools-native"
PREFERRED_PROVIDER_nativesdk-u-boot-mkimage = "nativesdk-u-boot-summit-tools"

PREFERRED_PROVIDER_u-boot-mkenvimage = "u-boot-summit-tools"
PREFERRED_PROVIDER_u-boot-mkenvimage-native = "u-boot-summit-tools-native"
PREFERRED_PROVIDER_nativesdk-u-boot-mkenvimage = "nativesdk-u-boot-summit-tools"

PREFERRED_PROVIDER_u-boot-mkeficapsule = "u-boot-summit-tools"
PREFERRED_PROVIDER_u-boot-mkeficapsule-native = "u-boot-summit-tools-native"
PREFERRED_PROVIDER_nativesdk-u-boot-mkeficapsule = "nativesdk-u-boot-summit-tools"

PREFERRED_PROVIDER_u-boot-dumpimage = "u-boot-summit-tools"
PREFERRED_PROVIDER_u-boot-dumpimage-native = "u-boot-summit-tools-native"
PREFERRED_PROVIDER_nativesdk-u-boot-dumpimage = "nativesdk-u-boot-summit-tools"
PREFERRED_RPROVIDER_u-boot-dumpimage = "u-boot-summit-tools-dumpimage"
